spring:
  application:
    name: SpringBoot By kishore

  datasource:
    url: jdbc:mysql://mysqldb:3306/employees
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 1234